In [1]:
import tensorflow as tf
import numpy as np

/Users/d3sm0/.virtualenvs/general/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [4]:
act_shape = 3

In [30]:
g = tf.get_default_graph()

In [31]:
del g

In [26]:
tf.reset_default_graph()

In [32]:
s = tf.convert_to_tensor(np.random.normal(size=(10, 1)), dtype=tf.float32)
s1 = tf.convert_to_tensor(np.random.normal(size=(10, 1)), dtype=tf.float32)

In [33]:
a = tf.convert_to_tensor(np.random.randint(0,3, size=10), dtype=tf.int32)

In [34]:
a = tf.one_hot(a, depth=3)

In [35]:
k = tf.layers.dense(s,units=act_shape, name='local')
k1 = tf.layers.dense(s1,units=act_shape, name='target')

In [36]:
v1 = tf.reduce_sum(tf.nn.softmax(k1) * k1, axis=1)

In [37]:
v = tf.reduce_sum(k * a, axis=1)

In [39]:
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

In [125]:
tf.gradients(v, )[0].eval()

NameError: name 'w' is not defined

In [99]:
v_grads = tf.gradients(v, tf.trainable_variables('local'))
v1_grads = tf.gradients(v1, tf.trainable_variables('target'))

In [116]:
v.eval()

array([ 0.03629377,  0.26632386, -0.19334826,  0.6561454 ,  0.21046188,
        0.28957933, -0.09705452,  1.3939091 , -0.6315174 ,  0.02366231],
      dtype=float32)

In [118]:
v1.eval()

array([-0.21408409, -0.45768952, -0.38213527, -0.39479017, -0.5666563 ,
        0.17271152,  0.78953123, -0.5036731 , -0.04246189, -0.40271878],
      dtype=float32)

In [103]:
l = tf.reduce_mean(v1-v)

In [114]:
tf.gradients(l, v)[0].eval()

array([-0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1, -0.1],
      dtype=float32)

In [112]:
tf.trainable_variables()[0].eval()

array([[ 0.5544516 , -0.34293205, -0.35786563]], dtype=float32)

In [ ]:
tf.app

In [ ]:
# first gradients should be of size x if derive wrt the function
# while if i derive wrt to the parameter is of size of the parameter

In [127]:
g = [(b-a,g) for a,b,g in zip(v_grads, v1_grads, tf.trainable_variables('local'))]

In [132]:
sess.run(tf.train.GradientDescentOptimizer(learning_rate=1.).apply_gradients(g))

In [135]:
tf.trainable_variables('local')[0].eval()

array([[0.5201163 , 1.2830005 , 0.22060281]], dtype=float32)

In [96]:
tf.train.GradientDescentOptimizer(learning_rate=1.).apply_gradients(((g, tf.trainable_variables('local')[0])))

TypeError: Tensor objects are not iterable when eager execution is not enabled. To iterate over this tensor use tf.map_fn.

In [85]:
tf.trainable_variables('local')[0]

<tf.Variable 'local/kernel:0' shape=(1, 3) dtype=float32_ref>